/** Tailwind-Konfiguration — Tokens 1:1 aus DESIGN.md / Stitch-Export.
 *  Nicht "neu designen": exakt dieselben Klassennamen, die die HTML-Screens nutzen. */
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#404943',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        outline: '#707973',
        'outline-variant': '#bfc9c1',
        'surface-tint': '#2c694e',
        primary: '#0f5238',
        'on-primary': '#ffffff',
        'primary-container': '#2d6a4f',
        'on-primary-container': '#a8e7c5',
        'inverse-primary': '#95d4b3',
        secondary: '#9d4300',
        'on-secondary': '#ffffff',
        'secondary-container': '#fd761a',
        'on-secondary-container': '#5c2400',
        tertiary: '#735c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#cea700',
        'on-tertiary-container': '#4e3e00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#b1f0ce',
        'primary-fixed-dim': '#95d4b3',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#0e5138',
        'secondary-fixed': '#ffdbca',
        'secondary-fixed-dim': '#ffb690',
        'on-secondary-fixed': '#341100',
        'on-secondary-fixed-variant': '#783200',
        'tertiary-fixed': '#ffe083',
        'tertiary-fixed-dim': '#eec200',
        'on-tertiary-fixed': '#231b00',
        'on-tertiary-fixed-variant': '#574500',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4',
      },
      spacing: {
        'container-margin': '16px',
        'stack-sm': '4px',
        base: '8px',
        'stack-lg': '24px',
        gutter: '12px',
        'stack-md': '12px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'label-lg': ['Inter'],
        'label-sm': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-xl': ['Inter'],
        'headline-xl-mobile': ['Inter'],
      },
      fontSize: {
        'label-sm': ['10px', { lineHeight: '14px', fontWeight: '500' }],
        'label-lg': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms],
};
